### ISSUE TITLE
Can't subclass the field in django 1.2

### ISSUE THREAD

**Issue by majdal** [shrubberysoft/django-picklefield#11]
I try to subclass PickledObjectField to be able to specifiy the form field and widget to use with it while staying DRY, but i get this error when i try to syncdb. Note that identical code has been tested on django 1.4, and works as expected.

I know that this is an outdated version of the package, but  @gintas 's branch does not have an issues section!

```
python manage.py syncdb --database=project
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/base.py", line 219, in execute
    self.validate()
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/core/management/validation.py", line 28, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/loading.py", line 61, in _populate
    self.load_app(app_name, True)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/majd/workspace/TEABudgeting/budgeting/models.py", line 2, in <module>
    from app_models.budget import Budget, Budget_form, Budget_grid
  File "/home/majd/workspace/TEABudgeting/budgeting/app_models/budget.py", line 56, in <module>
    class Budget(model.Model):
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/base.py", line 92, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/base.py", line 212, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/fields/subclassing.py", line 113, in contribute_to_class
    super(self.__class__, self).contribute_to_class(cls, name)

==================================================
many many many recursions of the same line later....
==================================================


  File "/home/majd/virtualenvs/26_tea/lib/python2.6/site-packages/django/db/models/fields/subclassing.py", line 113, in contribute_to_class
    super(self.__class__, self).contribute_to_class(cls, name)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by gintas** [comment]
Thanks for pointing out that my branch does not have an "Issues" tab! I had not realized that.

As for the exception, I can't help out much, especially since an old Django version is concerned. I am as mystified as you are.

**Comment by wdoekes** [comment]
This appears to work on the trouble I had with djcelery:

```
--- djcelery/picklefield.py 2016-03-01 17:48:04.033789000 +0100
+++ djcelery/picklefield.py 2016-03-02 11:56:26.820936159 +0100
@@ -38,10 +38,6 @@ NO_DECOMPRESS_HEADER = b'\x1e\x00r8d9qww
 if django.VERSION >= (1, 8):
     BaseField = models.Field
 else:
-    @with_metaclass(models.SubfieldBase, skip_attrs=set([
-        'db_type',
-        'get_db_prep_save'
-        ]))
     class BaseField(models.Field):  # noqa
         pass

@@ -117,6 +113,13 @@ class PickledObjectField(BaseField):
         return super(PickledObjectField, self) \
             .get_db_prep_lookup(*args, **kwargs)

+if django.VERSION < (1, 8):
+    PickledObjectField = (
+        with_metaclass(
+            models.SubfieldBase,
+            skip_attrs=set(['db_type', 'get_db_prep_save']))(
+                PickledObjectField))
+
 try:
     from south.modelsinspector import add_introspection_rules
 except ImportError:
```
